title: GOSH 2018 - Student Meetup
description: > # this means to ignore newlines until "baseurl:"
  This website is the official page for the GOSH 2018 student meetup at Gathering for Open Science Hardware conference at Tsinghua University, Shenzhen, China from 10th October to 13th October 2018
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goshmeetup2018.github.io/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/cloudypadmal
  - title: twitter
    url: https://twitter.com/Cloudypadmal
  - title: github
    url: https://github.com/CloudyPadmal
  - title: linkedin
    url: https://www.linkedin.com/in/m-padmal-5b042852/

# Build settings
markdown: kramdown
permalink: pretty
